spring.application.name=mher-system


mensaje.application=Aplicación Web con Spring MVC


#Copnfiguracion de Thymeleaf
spring.thymeleaf.prefix=classpath:/paginas/
spring.thymeleaf.suffix=.html


#DataSoure MariaDb
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/sisgcmher?useSSL=false&serverTimezone=UTC
spring.datasource.username=modulo2
spring.datasource.password=modulo2
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

